# Generated by Django 3.2.4 on 2021-06-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycart', '0002_auto_20210701_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
