# Generated by Django 3.2.4 on 2021-07-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycart', '0003_alter_mycart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(default='', max_length=80)),
                ('message', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
