# Generated by Django 3.2.4 on 2021-07-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycart', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_pincode',
            field=models.IntegerField(),
        ),
    ]
