# Generated by Django 3.2.4 on 2021-07-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mycart', '0009_auto_20210712_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addres',
            new_name='address',
        ),
    ]
