# Generated by Django 3.2.4 on 2021-07-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycart', '0010_rename_addres_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracker',
            fields=[
                ('Track_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('Track_desc', models.CharField(max_length=4000)),
                ('Track_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
