# Generated by Django 3.2.4 on 2021-08-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycart', '0011_ordertracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='sub_image11',
            field=models.ImageField(default='', upload_to='Mycart/images'),
        ),
        migrations.AddField(
            model_name='mycart',
            name='sub_image12',
            field=models.ImageField(default='', upload_to='Mycart/images'),
        ),
        migrations.AddField(
            model_name='mycart',
            name='sub_image13',
            field=models.ImageField(default='', upload_to='Mycart/images'),
        ),
        migrations.AddField(
            model_name='mycart',
            name='sub_image21',
            field=models.ImageField(default='', upload_to='Mycart/images'),
        ),
        migrations.AddField(
            model_name='mycart',
            name='sub_image22',
            field=models.ImageField(default='', upload_to='Mycart/images'),
        ),
        migrations.AddField(
            model_name='mycart',
            name='sub_image23',
            field=models.ImageField(default='', upload_to='Mycart/images'),
        ),
        migrations.AddField(
            model_name='mycart',
            name='sub_image31',
            field=models.ImageField(default='', upload_to='Mycart/images'),
        ),
        migrations.AddField(
            model_name='mycart',
            name='sub_image32',
            field=models.ImageField(default='', upload_to='Mycart/images'),
        ),
        migrations.AddField(
            model_name='mycart',
            name='sub_image33',
            field=models.ImageField(default='', upload_to='Mycart/images'),
        ),
    ]
