# Generated by Django 3.2.4 on 2021-09-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycart', '0012_auto_20210827_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='avl_colour',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mycart',
            name='brand',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mycart',
            name='specifation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
