# Generated by Django 3.2.4 on 2021-09-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycart', '0014_mycart_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
